server:
  port: 8080

logging:
  level:
    root: ${LOGGING_LEVEL:info}
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: INFO
            repository:
                query: INFO
    "[com.totem.food]": ${APP_LOGGING_LEVEL:debug}
    "[org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping]": ${SHOW_ENDPOINTS_LOGGING_LEVEL:info}
  pattern:
    level: "%clr(${LOG_LEVEL_PATTERN: [%X{x-request-id}] [%X{x-environment-id}] [%X{x-customer-id}] -%5p})"

spring:
  jackson:
    default-property-inclusion: non_null
  data:
    mongodb:
      uri: ${ORDER_MONGODB_URI:mongodb://root:qwe123@localhost:27017/totem-food-order?authSource=admin}

app:
  version: ^project.version^
  name: ^project.name^
  description: ^project.description^
  inspect_beans: ${INSPECT_BEANS:false}

ms:
  internal:
    topic:
      payment: ${PAYMENT_TOPIC:payment-topic}
    queue:
        payment_update_order: ${PAYMENT_QUEUE_UPDATE_ORDER:payment-update-order-queue}
    payment:
      url: ${MS_INTERNAL_PAYMENT:http://localhost:8082}
    customer:
      url: ${MS_INTERNAL_CUSTOMER:http://localhost:8081}

localstack:
  endpoint: http://localhost:4566
  region: us-east-1
  accessKey: teste
  secretKey: teste