server:
  port: 8080

logging:
  level:
    root: ${LOGGING_LEVEL:info}
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: INFO
            repository:
                query: INFO
    "[com.totem.food]": ${APP_LOGGING_LEVEL:debug}
    "[org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping]": ${SHOW_ENDPOINTS_LOGGING_LEVEL:info}
  pattern:
    level: "%clr(${LOG_LEVEL_PATTERN: [%X{x-request-id}] [%X{x-environment-id}] [%X{x-customer-id}] -%5p})"

spring:
  jackson:
    default-property-inclusion: non_null
  data:
    mongodb:
      uri: ${ORDER_MONGODB_URI:mongodb://root:qwe123@localhost:27017/totem-food-order?authSource=admin}

mail:
  smtp:
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:1025}
    username: ${SMTP_USERNAME:username}
    password: ${SMTP_PASSWORD:password}
    auth: ${SMTP_AUTH_ENABLED:false}
    tls: ${SMTP_TLS_ENABLED:false}
    email: ${SMTP_EMAIL:contato@totem.food.service.com.br}

app:
  version: ^project.version^
  name: ^project.name^
  description: ^project.description^
  inspect_beans: ${INSPECT_BEANS:false}

ms:
  internal:
    payment:
      url: ${MS_INTERNAL_PAYMENT:http://localhost:8082}
    customer:
      url: ${MS_INTERNAL_CUSTOMER:http://localhost:8081}